### ISSUE TITLE
Use module names in names of the cached files

### ISSUE THREAD

**Issue by prantlf** [runk/npm-proxy-cache#10]
The names of directories and files are computed using the first 8 characters of the md5 hash of the module URL.  It prevents name clashes and keeps the paths short, for example:

    module_cache/3/f/c/3fc88416
    module_cache/3/3/e/33e9f156
    module_cache/3/3/c/33c57016
    module_cache/3/2/d/32db7635.string
    module_cache/2/6/4/2649522b.tgz

However, makes the contents of the cache illegible; the original module URLs are "dissolved" in the hashes.  How about building in a flag to make the cache use the actual module name?  For example:

    module_cache/c/a/m/camelcase
    module_cache/c/a/m/camelcase-keys
    module_cache/s/u/p/superb
    module_cache/s/u/p/superb-1.1.0.tgz
    module_cache/u/n/d/underscore.string

It would enable easy querying without maintaining an additional database of module names and versions.  As long as all modules come from one (the public) registry, there should not be any name clashes.

*Motivation*

I'd like to use the proxy cache for daily builds of products, which have been released.  When rebuilt anytime in the future, it must be ensured that all needed build tools are available inside the company at the version which the particular product was built when released.  Being able to audit the cache directory and see what modules have been used would be very helpful.  No fancy queries for module meta-data would be needed; just being able to get the module name and version list would be enough.

Do you find it reasonable?  I tried [adding --friendly name option](https://github.com/prantlf/npm-proxy-cache/commit/8380b86bd50e406644bf2781f7c20d2f030b0009) to get this behaviour.  Would you accept a pull request?

**Comment by runk** [comment]
Hi there,

Very nice improvement actually.

- I wonder how does it work with quite short module names, e.g. `n` or something of that length.
- Would be great to have couple of unit tests in your PR

Other than that I'm happy to merge your changes :+1:

**Comment by prantlf** [comment]
Short module names work; the splice(0, 3) does not return more than the array contains.  If  I look at the specific module versions now, I think that I should cut the directory name before the version delimiting "-" (in "qs-2.2.4 tgz").  Although it works now, the "-" in the path looks weird.  The path of "qs-2.2.4.tgz" could be "q/s/qs-2.2.4.tgz" instead of the current "q/s/-/qs-2.2.4.tgz".

    module_cache/s/c/m/scmp
    module_cache/s/c/m/scmp-1.0.0.tgz
    module_cache/q/s/qs
    module_cache/q/s/-/qs-2.2.4.tgz
    module_cache/q/q
    module_cache/l/o/d/lodash

You're right - I must add some tests.  Your tests still run green after the change :-)  I'll do it and prepare the PR.  Thanks!

**Comment by prantlf** [comment]
Thanks for merging the feature!  Could you publish the 0.2.2 in npmjs, please?  Thank you!

**Comment by runk** [comment]
Oops, my bad. Published!

On 3 March 2015 at 04:47, Ferdinand Prantl <notifications@github.com> wrote:

> Thanks for merging the feature! Could you publish the 0.2.2 in npmjs,
> please? Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/runk/npm-proxy-cache/issues/10#issuecomment-76760993>.
>



-- 
Kind Regards,

Dmitry Shirokov

**Comment by prantlf** [comment]
Great, thanks!  It works well.  This issue can be closed.
