### ISSUE TITLE
work with private registry

### ISSUE THREAD

**Issue by mikeya** [runk/npm-proxy-cache#14]
We're using nexus to cache our internal npm modules. However our nexus is stored in AWS and I want to setup a local proxy in our building to cache requests from nexus. Our Nexus repo requires auth, but the _auth param from my local doesn't seem to be getting passed through the npm-proxy-cache.

**Comment by runk** [comment]
What's the nexus? I imagine it's not an android phone right :)

**Comment by mikeya** [comment]
Hahah sorry nexus is a proxy server used to manage dependencies. 

https://books.sonatype.com/nexus-book/reference/npm-configuring.html


Regardless I want to use the node-proxy-cache with an internal registry.

https://docs.npmjs.com/misc/registry

**Comment by runk** [comment]
Not sure I follow docs. From what I understand your nexus repo should have read access for unprivilidged users. And authenticated when you want to publish packages and silimar (write access). Can you reference me to the docs how exactly auth supposed to work?

**Comment by runk** [comment]
Closing as stale
