### ISSUE TITLE
Log Path

### ISSUE THREAD

**Issue by emn178** [runk/npm-proxy-cache#17]
Hi,

Can you add an option to set log path?

Thanks and best regards.

**Comment by runk** [comment]
Hi, there's no such option yet. Feel free to add it and post a pull request :+1:

**Comment by someuser77** [comment]
@runk would you rather specify a log path to write the logs to or perhaps it will be better to specify a log4js config file path?

**Comment by runk** [comment]
I don't mind adding a parameter for a log path, but separate log4js config sounds too much. You can always fork this repo and make changes in it if you need something very specific. Otherwise feel free to add an option for log path :+1:
