### ISSUE TITLE
Not able to install offline from cache

### ISSUE THREAD

**Issue by keberox** [runk/npm-proxy-cache#19]
Hi @runk,  from what understand npm-proxy-cache will allow me to correctly use the npm cache I have in the local machine - since internal logic to handle this in NPM itself has been broken for a while now.

I have npm-proxy-cache running and listening to port 8080, when I execute like you show in the examples:
npm --proxy http://localhost:8080 --https-proxy http://localhost:8080 --strict-ssl false install gulp@3.8.11

then npm-proxy-cache throws this  on the console
 [WARN] proxy - direct http://registry.npmjs.org/gulp

it seems it is trying to call the registry, but what I want is to use the files in ~/.npm cache.

The machine currently has no access to the internet what is why I was willing to try to use something that will allow me to install from local npm cache.

I an using RedHat 6
running node 4.2.2

Did I get something wrong?

Thanks!

**Comment by Siggen** [comment]
Hi,

I'm using the following bash script to do that :

```
#!/bin/sh

SOURCE_URL=$1
LIBFILE=$2
if [ -z "$SOURCE_URL" -o -z "$LIBFILE" ]; then
        echo "Usage : $(basename "$0") <source-url> <lib-file>" >&2
        exit 1
fi

if [ ! -d "data" ]; then
        echo "Script must be called at the 'data' directory level." >&2
        exit 1
fi

FULL_HASH=$(echo -n "$SOURCE_URL" | md5sum -)
#echo "FULL_HASH =" $FULL_HASH

REL_PATH=$(echo -n "$FULL_HASH" | sed -r "s!(.)(.)(.)(.....).*!data/\1/\2/\3!")
#echo "REL_PATH =" $REL_PATH
mkdir -p $REL_PATH

EXTENSION="${LIBFILE##*.}"
FILENAME=$(echo -n "$FULL_HASH" | sed -r "s!(.)(.)(.)(.....).*!data/\1/\2/\3/\1\2\3\4!")
FILENAME=$FILENAME.$EXTENSION
#echo "FILENAME =" $FILENAME

echo "Copying" $LIBFILE "to" $FILENAME "..."
cp -f $LIBFILE $FILENAME
```

You need to provide two parameters : 
  - URL of the internet package
  - local copy of the package

Example :

```
./insert_lib.sh http://cdn.bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2 phantomjs-1.9.7-linux-x86_64.tar.bz2
```

Hope it helps !

**Comment by dmillerme7** [comment]
That might work if you have internet access but if the machine doesn't have internet access?

**Comment by Siggen** [comment]
I usually download the package from another machine and then copy it (scp) to the cache-hosting's machine. Yes, that's a bit tedious.

**Comment by runk** [comment]
@keberox what this module does is proxying all requests and caching responses. That said, you need to have internet at least at first when you create a cache. Next install you do will not be downloaded from the internet. There're several "layers":

**built-in npm cache** > **proxy cache (this module)** > **npm registry**

Hope that helps
