### ISSUE TITLE
DEPTH_ZERO_SELF_SIGNED_CERT error

### ISSUE THREAD

**Issue by pnorman** [runk/npm-proxy-cache#21]
Same commands as #20, but a different error

With this shell script I get a DEPTH_ZERO_SELF_SIGNED_CERT error

```sh
npm config set proxy http://192.168.1.1:7288/
npm config set https-proxy http://192.168.1.1:7288/
npm config set strict-ssl false
npm install windshaft
```

```
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v11-linux-x64.tar.gz
node-pre-gyp http DEPTH_ZERO_SELF_SIGNED_CERT (falling back to source compile with node-gyp)

```

I'm running npm-proxy-cache from source with `
./bin/npm-proxy-cache -h 192.168.1.1 -p 7288 -t 7200` on another machine.

**Comment by runk** [comment]
What node version you use? I cannot reproduce it with 0.12

**Comment by pnorman** [comment]
```sh
# node --version
v0.10.25
# npm --version
1.3.10
```

What is packaged for ubuntu trusty.

**Comment by runk** [comment]
Cannot reproduce that error with given versions on Mac OS :(

Published npm-proxy-cache@0.3.3. It has `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0" ` trick as explained here https://github.com/request/request/issues/418

**Comment by pnorman** [comment]
Wouldn't I need to do something on the machine running npm, not the one running `npm-proxy-cache`?

**Comment by runk** [comment]
Nope, it should not make much difference I guess

**Comment by pnorman** [comment]
Updated npm-proxy-cache, but no change.

I have a fix, doing a PR.
