### ISSUE TITLE
Cache TTL is always 30 minutes, even when you try to set it by passing in a parameter

### ISSUE THREAD

**Issue by amritp55** [runk/npm-proxy-cache#27]
The cache's time to live is always 30 minutes. Even when starting the proxy with a parameter (npm-proxy-cache --ttl [1])

This should expire the cache after one second, and should grab it directly. However it grabs the node packages from the cache still. After 30 minutes it expires the cache.

**Comment by runk** [comment]
Can you try

```
npm-proxy-cache --ttl 1
```

without square brackets?

**Comment by amritp55** [comment]
It works perfectly. Thanks
