### ISSUE TITLE
Does it work with a proxy?  :)

### ISSUE THREAD

**Issue by Klortho** [runk/npm-proxy-cache#31]
My problem is that I use a proxy server to access a private registry at my work, but it is too slow. This module looks like it could help me, but (ironically) it *is* a proxy server, too, so I'd be setting up a "two hop" proxy. But, it's not clear to me that this supports accessing the registry through a proxy.

**Comment by runk** [comment]
Well, it uses `request` module under the bonnet, https://github.com/request/request. Hence, you can try to start it with with env variables like this:

```
HTTP_PROXY=http://mycorpproxy:8080 npm-proxy-cache 
```

see https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables
