### ISSUE TITLE
Error to empty request

### ISSUE THREAD

**Issue by Webysther** [runk/npm-proxy-cache#34]
Proxy return error after a simple `curl -I http://localhost:8080`

![uva-proxy](https://cloud.githubusercontent.com/assets/750007/17637260/c1538000-60b8-11e6-976d-638fc847e1dc.png)

**Comment by Webysther** [comment]
Fixed on [docker-npm-proxy-cache PR](https://github.com/kudos/docker-npm-proxy-cache/pull/1) just for dont stop.

**Comment by runk** [comment]
I'd appreciate if you'd create a PR for this issue
