### ISSUE TITLE
How to work with private npm such as sinopia

### ISSUE THREAD

**Issue by juneidysoo** [runk/npm-proxy-cache#35]
Hi there,

First of all, it's a great work and saved me a lot of hassle on working with docker containers by having an npm cache server. I wonder if it would work with private npm that requires authentication such as sinopia? I have added .npmrc but npm-proxy-cache doesn't seems to check .npmrc for authentication token.

**Comment by runk** [comment]
Hey, I'll have a look how to make it happen.

**Comment by runk** [comment]
Published in `npm-proxy-cache@0.6.0`, took long time to find time to fix this problem, apologies.
