### ISSUE TITLE
Unable to access private package.

### ISSUE THREAD

**Issue by sfurnival** [runk/npm-proxy-cache#39]
Forgive me if I've missed something obvious, but it seems npm-proxy-cache is unable to download private packages under an organization namespace. (Even when logged into npm correctly)
```
npm ERR! Unexpected token S in JSON at position 0
npm ERR! Status 404 returned
```

**Comment by sfurnival** [comment]
```bash
npm ERR! Unexpected token S in JSON at position 0
npm ERR! Status 404 returned
```

**Comment by juneidysoo** [comment]
might be related to #35

**Comment by runk** [comment]
Thanks for feedback! `npm-proxy-cache@0.6.0` is out.
