### ISSUE TITLE
NPM Publish Support

### ISSUE THREAD

**Issue by sfurnival** [runk/npm-proxy-cache#41]
Firstly, thanks again for your great work guys!

On 0.6.0, trying to publish a repository has authentication problems, (yes, I'm logged in correctly):

```bash
npm ERR! publish Failed PUT 401
npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/usr/local/nvm/versions/node/v6.9.1/bin/node" "/usr/local/nvm/versions/node/v6.9.1/bin/npm" "publish"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code E401

npm ERR! You must be logged in to publish packages : <redacted>
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

This might not be a priority for you guys, since I imagine you'd have run into it already if you were doing any publishing.  That said, I don't mind adding the functionality and sending a PR, but I'd love if you could point me in the right direction on where/how you see this fitting into the existing code.

**Comment by runk** [comment]
Hey!

I think problem is in `bypass` fn: https://github.com/runk/npm-proxy-cache/blob/master/lib/proxy.js#L105. Module caches only GET requests, other and proxies "as is". 

Guess we need to abstract https://github.com/runk/npm-proxy-cache/blob/master/lib/proxy.js#L95  code for passing headers (incl authorization) into separate function and use it in both places.

I feel a little uncomfortable that there're no tests for proxy.js - would be awesome if you'd add some. I don't use this module personally and cannot justify spending more time on it raising coverage to a decent level :(

**Comment by sfurnival** [comment]
Thanks, I'll see what I can do!

**Comment by FrankZZ** [comment]
@sfurnival I've added a test for the "Disable metadata caching" feature in `proxy.js`, which was merged yesterday.

You can use that as a base for the tests.

**Comment by runk** [comment]
Not sure it's still the case. Closing it for now. Let me know if problem persists.
