### ISSUE TITLE
cache server is sending my request as http instead of https

### ISSUE THREAD

**Issue by juneidysoo** [runk/npm-proxy-cache#42]
When trying to retrieving my package (say `blah`) from sinopia, the request being sent is `https://sinopia.server/blah/`. But `npm-proxy-cache` then send the request to `http://sinopia.server/blah/-/blah-some.version.tgz`.

Somehow `npm-proxy-cache` fail to detect if my request is `https`

**Comment by runk** [comment]
That's odd. Can you start the proxy with `--verbose` flag to get more details?

I'd appreciate if you'd add a couple of `console.log`s somewhere around https://github.com/runk/npm-proxy-cache/blob/master/lib/proxy.js#L83 in order to get more information.

**Comment by juneidysoo** [comment]
what variable would you like to have logged?

**Comment by juneidysoo** [comment]
here's the sample log
[log.txt](https://github.com/runk/npm-proxy-cache/files/591078/log.txt)

the console.log is `console.log(cache, dest, schema, req.url);`

**Comment by runk** [comment]
It can be related to https://github.com/runk/npm-proxy-cache/blob/master/lib/proxy.js#L86 `client.pair` check. The handler is used for both http and https servers, that line determines which protocol it uses.

**Comment by juneidysoo** [comment]
`req.client.pair` is undefined although `req.connection.encrypted` gives me true. Which node version are you using? I'm using node 6.7

**Comment by runk** [comment]
I'm not using this module at all right now.

Can you craft a pr that checks for either `req.client.pair` or `req.connection.encrypted`?

**Comment by runk** [comment]
`npm-proxy-cache@0.6.1` is out
