### ISSUE TITLE
folha/npm-proxy-cache overrides the default ttl

### ISSUE THREAD

**Issue by thuey** [runk/npm-proxy-cache#46]
`npm-proxy-cache` has been great, but there was one thing that threw us off for a while that could trip someone else up. The official docker image for this folha/npm-proxy-cache overrides the default ttl: https://github.com/FolhaSP/docker-npm-proxy-cache/blob/master/Dockerfile#L10. I would suggest either not doing that or at least documenting it better. It took me a while to figure out why the cache wasn't getting any updates.

**Comment by runk** [comment]
Hey - unfortunately I'm not controlling that repo, you're welcome to send a PR with Dockerfile and good docs. I'm happy to accept it. :)

**Comment by FrankZZ** [comment]
@runk PR sent.
