### ISSUE TITLE
Use separate ttl for detecting compatible versions

### ISSUE THREAD

**Issue by thuey** [runk/npm-proxy-cache#47]
I think it's great that npm-proxy-cache caches actual packages. However, I'm running into a situation where I publish frequently and the modules that depend on those published packages pull frequently. That means that I only have one option: set the ttl lower so that npm-proxy-cache will detect new versions faster, but take the overhead of frequent cache invalidation on existing package versions.

Maybe I'm misunderstanding how npm-proxy-cache works, but it seems to me like you shouldn't even need to expire existing packages. Since npm doesn't allow you to overwrite a version, shouldn't you just be able to cache downloaded packages indefinitely?

**Comment by runk** [comment]
Yeah - right now module doesn't differentiate between different data types (package/meta info) and resources. It caches all content using same simple principle. I'm not using this module personally anymore - you're welcome to send a PR with improvements.

**Comment by thuey** [comment]
Okay--will do. Can you think of a reason why it would be a bad idea to cache resources indefinitely?

**Comment by cadavre** [comment]
The fact is TTL for packages is non-sense in this case, because once deployed version on npm – it will never change, so... it doesn't require cache expiration. I would say that app should check for packages downloaded longer than TTL and them remove files from cache. This would simply remove old packages that are no longer used in projects.

For me, metadata should never be cached.

**Comment by runk** [comment]
I'd be good to be able to specify different caching strategy via an option. I can think of two of them right now.

1. Infinitive cache for packages, no cache (or very small) for meta
1. Cache everything with same ttl

**Comment by cadavre** [comment]
Any decisions here? Implementation?

**Comment by FrankZZ** [comment]
@cadavre @runk 
I have created a PR with the option to enable or disable metadata caching completely.
