### ISSUE TITLE
Endless loop when accessing http://localhost:8080 directly

### ISSUE THREAD

**Issue by nknapp** [runk/npm-proxy-cache#48]
Nice project, it will definetely help us save bandwidth when installing npm-modules.

The following will put this module into an endless loop (at least on Linux)

```bash
npm install -g npm-proxy-cache
npm-proxy-cache &
curl http://localhost:8080
```

I am now running npm-proxy-cache in a docker-container where the 8082 is mapped on 8080 within the container. Still, if you do

```bash
export http_proxy=http://localhost:8082
curl http://localhost:8080
```

The endless-loop starts again.

**Comment by nknapp** [comment]
I would probably 

* create a random header name `X-NPM-PROXY-CACHE-<random-number>`, 
* send this header along with every proxied request
* reject any request that has this header set

This shoud make sure that requests never pass this proxy twice.

**Comment by runk** [comment]
Thanks for the feedback, merged your PR. 

`v0.7.0` is out.
