### ISSUE TITLE
Concurrent access to files that are beeing cached fails

### ISSUE THREAD

**Issue by Cirrus0** [runk/npm-proxy-cache#62]
Observed behaviour:
If 2 or more builds are triggered at the same time npm install fails because of incorrect checksums / invalid archives

Guess:
Proxy gets request 1, notices he does not have the file, starts downloading into file
Proxy gets request 2, notices he "has" the file, serves the file, the file is broken (because incomplete)

Suggestion:
- The proxy could keep checksums as well as files and do a check before serving the file
- The proxy could download files in a way that only makes them available after they are downloaded completely

Both of these could result in a file beeing downloaded multiple times, while the first suggestion could also produce a noticable slowdown of operations

**Comment by runk** [comment]
Hi! Thanks for the report, I think it makes sense what you're saying, let me see what are the options.

**Comment by runk** [comment]
Solved in #63. Version v1.0.4 is out.
