### ISSUE TITLE
Does this work with private packages?

### ISSUE THREAD

**Issue by simlu** [runk/npm-proxy-cache#69]

**Comment by JohanVandeplas** [comment]
anyone tried yet?

**Comment by FrankZZ** [comment]
Short answer: yes.
Long answer: npm-proxy-cache forwards the `Authorization` header towards the npm registry so we support private packages, given you are authorized and sending the authorization token.

**Comment by runk** [comment]
Thanks @FrankZZ.

Closing the ticket.
